import { StyleSheet, Dimensions } from "react-native";

// export default StyleSheet.create({
//   screenContainer: {
//     flex: 1,
//     backgroundColor: "#f5f5f5",
//   },
//   content: {
//     padding: 16,
//   },
//   centerContainer: {
//     flex: 1,
//     justifyContent: "center",
//     alignItems: "center",
//     backgroundColor: "#f5f5f5",
//   },
//   loadingText: {
//     marginTop: 16,
//     fontSize: 16,
//     color: "#666",
//   },
//   title: {
//     fontSize: 24,
//     fontWeight: "bold",
//     marginBottom: 20,
//     color: "#333",
//   },
//   cardGrid: {
//     flexDirection: "row",
//     flexWrap: "wrap",
//     justifyContent: "space-between",
//     marginBottom: 20,
//   },
//   card: {
//     flexDirection: "row",
//     alignItems: "center",
//     padding: 16,
//     backgroundColor: "white",
//     borderRadius: 12,
//     marginBottom: 5,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.1,
//     shadowRadius: 4,
//     elevation: 3,
//   },
//   cardHeader: {
//     flexDirection: "row",
//     alignItems: "center",
//   },
//   cardTitle: {
//     fontSize: 16,
//     fontWeight: "600",
//     marginLeft: 8,
//     color: "#333",
//   },
//   header: {
//     backgroundColor: "white",
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.1,
//     shadowRadius: 4,
//     elevation: 3,
//   },
//   headerTitle: {
//     fontSize: 18,
//     fontWeight: "600",
//     color: "#333",
//   },
//   drawerContent: {
//     backgroundColor: "white",
//   },
//   drawerHeader: {
//     padding: 16,
//     borderBottomWidth: 1,
//     borderBottomColor: "#f0f0f0",
//   },
//   drawerTitle: {
//     fontSize: 20,
//     fontWeight: "bold",
//     color: "#333",
//   },
//   drawerLabel: {
//     fontSize: 16,
//     fontWeight: "500",
//   },
//   drawerFooter: {
//     borderTopWidth: 1,
//     borderTopColor: "#f0f0f0",
//     marginTop: 16,
//   },
//   logoutLabel: {
//     color: "#FF3B30",
//   },
//   profileSection: {
//     flexDirection: "row",
//     alignItems: "center",
//     padding: 16,
//     backgroundColor: "white",
//     borderRadius: 12,
//     marginBottom: 20,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.1,
//     shadowRadius: 4,
//     elevation: 3,
//   },
//   avatar: {
//     width: 60,
//     height: 60,
//     borderRadius: 30,
//   },
//   profileName: {
//     fontSize: 18,
//     fontWeight: "bold",
//     color: "#333",
//   },
//   profileSubtitle: {
//     fontSize: 14,
//     color: "#666",
//   },
// });

export default StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  content: {
    padding: 16,
  },
  container: { flex: 1, backgroundColor: "#f8f9fa", padding: 16 },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  // title: {
  //   fontSize: 24,
  //   fontWeight: "bold",
  //   marginBottom: 20,
  //   color: "#333",
  // },
  cardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  // card: {
  //   flexDirection: "row",
  //   alignItems: "center",
  //   padding: 16,
  //   backgroundColor: "white",
  //   borderRadius: 12,
  //   marginBottom: 5,
  //   shadowColor: "#000",
  //   shadowOffset: { width: 0, height: 2 },
  //   shadowOpacity: 0.1,
  //   shadowRadius: 4,
  //   elevation: 3,
  // },
  // cardHeader: {
  //   flexDirection: "row",
  //   alignItems: "center",
  // },
  // cardTitle: {
  //   fontSize: 16,
  //   fontWeight: "600",
  //   marginLeft: 8,
  //   color: "#333",
  // },
  // header: {
  //   backgroundColor: "white",
  //   shadowColor: "#000",
  //   shadowOffset: { width: 0, height: 2 },
  //   shadowOpacity: 0.1,
  //   shadowRadius: 4,
  //   elevation: 3,
  // },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
  },
  drawerContent: {
    backgroundColor: "white",
  },
  drawerHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  drawerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  drawerLabel: {
    fontSize: 16,
    fontWeight: "500",
  },
  drawerFooter: {
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    marginTop: 16,
  },
  logoutLabel: {
    color: "#FF3B30",
  },
  profileSection: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "white",
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  profileSubtitle: {
    fontSize: 14,
    color: "#666",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  title: { fontSize: 24, fontWeight: "bold" },
  description: { fontSize: 14, color: "#6c757d" },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  fillButton: {
    marginTop: 16,
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  fillButtonText: { color: "#fff", fontWeight: "600", fontSize: 16 },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e9ecef",
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  cardHeader: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  cardContent: {
    // Add any desired styling for card content here
    marginTop: 4,
  },
  icon: { fontSize: 16 },
  cardTitle: { fontSize: 16, fontWeight: "600" },
  boldText: { fontWeight: "600", fontSize: 14 },
  mutedText: { fontSize: 12, color: "#6c757d" },
  smallText: { fontSize: 14 },
  qrCodePlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    height: 80,
    width: 80,
    alignSelf: "center",
    marginTop: 8,
    backgroundColor: "#e9ecef",
    borderRadius: 4,
  },
  badgeContainer: { flexDirection: "row", flexWrap: "wrap", marginTop: 4 },
  badge: {
    backgroundColor: "#e9ecef",
    borderRadius: 16,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginRight: 4,
    marginBottom: 4,
  },
  badgeText: { fontSize: 12, fontWeight: "500", color: "#495057" },

  chartPlaceholder: {
    height: 120,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e9ecef",
    borderRadius: 4,
    marginTop: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
  },
  // avatar: {
  //   width: 64,
  //   height: 64,
  //   borderRadius: 32,
  //   backgroundColor: "#e9ecef",
  // },
});
